apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spamcop.fullname" . }}-credentials
type: Opaque
data:
  USERNAME: {{ .Values.username | required "username is required" | b64enc | quote }}
  PASSWORD: {{ .Values.password | required "password is required" | b64enc | quote }}