apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "osa.fullname" . }}-database
  labels:
    {{- include "osa.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.storage | quote }}
  storageClassName: {{ .Values.persistence.className }}