# Default values for osa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: moray95/osa
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

dashboard:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP

persistence:
  storage: 1Gi
  className: 'hdd'